spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydb?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: true
upload:
  open: true
  base-dir: E:\data\git\easypass-ui\dist
  max-file-size: 2MB
  max-request-size: 10MB
  default-domain: "http://images.user.xxx.com"
  module-types:
  - name: "user"
    file-path: "user"
    upload-types:
    - name: "images"
      store-type: "LOCAL"
    - name: "videos"
      store-type: "LOCAL"
  - name: "car"
    file-path: "car"
    upload-types:
    - name: "images"
      store-type: "LOCAL"
    - name: "videos"
      store-type: "LOCAL"
